apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}-secret
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  QUEUE_PASSWORD: {{ .Values.secrets.queuePassword | quote }}
