replicaCount: 1

config:
  service:
    env: development
  log:
    level: debug
  queue:
    host: ""   # set via: --set config.queue.host=<rabbitmq-host>

hpa:
  enabled: false

pdb:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi
