apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  labels:
    {{- include "user-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | quote }}
  QUEUE_PASSWORD: {{ .Values.secrets.queuePassword | quote }}
